- name: Create secrets directory
  file:
    path: /etc/flashdb
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy secrets into that location
  copy:
    src: "{{ env }}/secrets.env"
    dest: /etc/flashdb/secrets.env
    owner: root
    group: docker
    mode: "0640"
