# Generated by Django 6.0.3 on 2026-04-08 05:58

import db_query.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
                ('config_tar', models.BinaryField(blank=True, null=True)),
                ('errlog', models.TextField(blank=True, null=True)),
                ('stdlog', models.TextField(blank=True, null=True)),
                ('result_filepath', models.CharField(blank=True, max_length=100, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('run_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('invertf', models.BooleanField(blank=True, null=True)),
                ('maskf', models.BooleanField(blank=True, null=True)),
                ('mask_invertf', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detect_run',
            },
        ),
        migrations.CreateModel(
            name='SpectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
                ('config_tar', models.BinaryField(blank=True, null=True)),
                ('errlog', models.TextField(blank=True, null=True)),
                ('stdlog', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('run_tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'spect_run',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=100)),
                ('shortname', db_query.models.CharFieldFixed(blank=True, max_length=5, null=True)),
                ('component_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ra_hms_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('dec_dms_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('ra_deg_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('dec_deg_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('processstate', models.CharField(max_length=50)),
                ('opd_plotname', models.CharField(blank=True, max_length=100, null=True)),
                ('flux_plotname', models.CharField(blank=True, max_length=100, null=True)),
                ('opd_image', models.BinaryField(blank=True, null=True)),
                ('flux_image', models.BinaryField(blank=True, null=True)),
                ('fluxfilter', db_query.models.RealField(blank=True, null=True)),
                ('flux_cutoff', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="flux_cutoff must be either 'ABOVE' or 'BELOW'", regex='^(ABOVE|BELOW)$')])),
                ('flux_peak', db_query.models.RealField(blank=True, null=True)),
                ('flux_int', db_query.models.RealField(blank=True, null=True)),
                ('mode_num', models.IntegerField(blank=True, null=True)),
                ('invert_mode_num', models.IntegerField(blank=True, null=True)),
                ('mask_mode_num', models.IntegerField(blank=True, null=True)),
                ('invert_mask_mode_num', models.IntegerField(blank=True, null=True)),
                ('ln_mean', db_query.models.RealField(blank=True, null=True)),
                ('invert_ln_mean', db_query.models.RealField(blank=True, null=True)),
                ('mask_ln_mean', db_query.models.RealField(blank=True, null=True)),
                ('invert_mask_ln_mean', db_query.models.RealField(blank=True, null=True)),
                ('spectral_date', models.DateTimeField(blank=True, null=True)),
                ('detection_date', models.DateTimeField(blank=True, null=True)),
                ('invert_detection_date', models.DateTimeField(blank=True, null=True)),
                ('mask_detection_date', models.DateTimeField(blank=True, null=True)),
                ('sbid_id', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('has_siblings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'component',
                'constraints': [models.CheckConstraint(condition=models.Q(('flux_cutoff__in', ['ABOVE', 'BELOW'])), name='check_flux')],
            },
        ),
        migrations.CreateModel(
            name='SBID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbid_num', models.IntegerField()),
                ('spect_runid', models.IntegerField(blank=True, null=True)),
                ('detect_runid', models.IntegerField(blank=True, null=True)),
                ('spectralf', models.BooleanField(blank=True, null=True)),
                ('detectionf', models.BooleanField(blank=True, null=True)),
                ('ascii_tar', db_query.models.OIDField(blank=True, help_text='PostgreSQL OID', null=True)),
                ('detect_tar', db_query.models.OIDField(blank=True, help_text='PostgreSQL OID', null=True)),
                ('quality', models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('UNCERTAIN', 'UNCERTAIN'), ('REJECTED', 'REJECTED'), ('NOT_VALIDATED', 'NOT_VALIDATED')], max_length=50, null=True)),
                ('version', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('spectral_config_tar', db_query.models.OIDField(blank=True, null=True)),
                ('detect_config_tar', db_query.models.OIDField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('pointing', models.TextField(blank=True, null=True)),
                ('detect_results', models.BinaryField(blank=True, null=True)),
                ('invert_detectionf', models.BooleanField(blank=True, null=True)),
                ('invert_detect_results', models.BinaryField(blank=True, null=True)),
                ('invert_results', models.TextField(blank=True, null=True)),
                ('invert_detect_runid', models.IntegerField(blank=True, null=True)),
                ('invert_detect_tar', models.BigIntegerField(blank=True, help_text='PostgreSQL OID', null=True)),
                ('mask_detectionf', models.BooleanField(blank=True, null=True)),
                ('mask', models.TextField(blank=True, null=True)),
                ('mask_detect_results', models.BinaryField(blank=True, null=True)),
                ('mask_results', models.TextField(blank=True, null=True)),
                ('mask_detect_tar', models.BigIntegerField(blank=True, help_text='PostgreSQL OID', null=True)),
                ('mask_detect_runid', models.IntegerField(blank=True, null=True)),
                ('mask_invert_runid', models.IntegerField(blank=True, null=True)),
                ('mask_invertf', models.BooleanField(blank=True, null=True)),
                ('mask_invert_detect_results', models.BinaryField(blank=True, null=True)),
                ('mask_invert_results', models.TextField(blank=True, null=True)),
                ('publicf', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sbid',
                'constraints': [models.CheckConstraint(condition=models.Q(('quality__in', ['GOOD', 'BAD', 'UNCERTAIN', 'REJECTED', 'NOT_VALIDATED'])), name='check_types')],
            },
        ),
    ]
