services:
  submit-hpc-job:
    image: aussrc/flash_jobs:${FLASH_JOB_IMAGE_TAG}

    env_file:
      - /etc/flashdb/secrets.env

    volumes:
      - /srv/flashdb/job-data:/data
      - /home/job/.ssh/setonix:/home/app/.ssh/setonix:ro
