services:
  web:
    build: .
    restart: always
    expose:
      - "8000"
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles

    environment:
      - DB_HOST=host.docker.internal

  nginx:
    image: nginx:alpine
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/media:ro
      - static_data:/app/staticfiles
      - ./ssl:/etc/nginx/ssl:ro

    depends_on:
      - web

volumes:
  media_data:
  static_data: